name: Build and push docker images

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-beta"
      - "v*.*.*-alpha"
#    branches:
#      - "main"
  workflow_dispatch:
    inputs:
      build_profile:
        type: choice
        description: 'Select the build profile'
        required: true
        options:
          - "alpha"
          - "beta"
          - "release"
      version_tag:
        type: string
        description: 'Version tag for the docker image (optional, defaults to the git ref name)'
        required: false
        default: "vX.Y.Z"

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: git.jonasbernard.de
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build frontend
        working-directory: ./workshops-frontend
        env:
          VERSION_TAG: ${{ github.event.inputs.version_tag || github.ref_name }}
          BUILD_PROFILE: ${{ github.event.inputs.build_profile || endsWith(github.ref_name, 'alpha') && 'alpha' || endsWith(github.ref_name, 'beta') && 'beta' || 'release' }}
        run: |
          IMAGE="git.jonasbernard.de/jonas/gruppen-tool-frontend:${VERSION_TAG}"
          docker build -t "${IMAGE}" --build-arg REACT_APP_VERSION=${VERSION_TAG} $(cat docker.${BUILD_PROFILE}.build.args | sed 's@^@--build-arg @g' | paste -s -d " ") .

      - name: Push frontend
        env:
          VERSION_TAG: ${{ github.event.inputs.version_tag || github.ref_name }}
        run: |
          IMAGE="git.jonasbernard.de/jonas/gruppen-tool-frontend:${VERSION_TAG}"
          docker push "${IMAGE}"
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: git.jonasbernard.de
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build backend
        working-directory: ./workshops-backend
        env:
          VERSION_TAG: ${{ github.event.inputs.version_tag || github.ref_name }}
        run: |
          IMAGE="git.jonasbernard.de/jonas/gruppen-tool-backend:${VERSION_TAG}"
          docker build -t "${IMAGE}" .

      - name: Push backend
        env:
          VERSION_TAG: ${{ github.event.inputs.version_tag || github.ref_name }}
        run: |
          IMAGE="git.jonasbernard.de/jonas/gruppen-tool-backend:${VERSION_TAG}"
          docker push "${IMAGE}"
  
  backend-v2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: git.jonasbernard.de
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build backend-v2
        working-directory: ./workshops-backend-v2
        env:
          VERSION_TAG: ${{ github.event.inputs.version_tag || github.ref_name }}
        run: |
          IMAGE="git.jonasbernard.de/jonas/gruppen-tool-backend-v2:${VERSION_TAG}"
          docker build -t "${IMAGE}" .

      - name: Push backend-v2
        env:
          VERSION_TAG: ${{ github.event.inputs.version_tag || github.ref_name }}
        run: |
          IMAGE="git.jonasbernard.de/jonas/gruppen-tool-backend-v2:${VERSION_TAG}"
          docker push "${IMAGE}"
  
